version: '3.8'

services:
  backend:
    image: mashi
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: [ dev.env ]
    ports:
    - 18080:${PORT}
    volumes:
    - .:/mashi
    command: make compose_dev_test_and_run

