version: '3.8'

services:
  backend:
    image: mashi
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: [ .env ]
    ports:
    - 8080:${PORT}
    volumes:
    - .:/mashi
    command: air

