FROM golang:latest

WORKDIR /mashi

COPY ./go.mod .
RUN go mod download

RUN go install github.com/cosmtrek/air@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

