version: '3.8'

services:
  backend:
    image: mashi
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file: [ dev.env ]
    ports: [ "18080:${PORT}" ]
    depends_on:
      - db
    volumes:
    - .:/mashi
    command: make compose_dev_test_and_run
  db:
    image: postgres:15.0-bullseye
    restart: always
    environment:
      - POSTGRES_USER=mashi
      - POSTGRES_PASSWORD=123456789
    ports: [5432:5432]
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports: [18081:8080]
    restart: always




volumes:
  pgdata:
    driver: local
