

CREATE TABLE IF NOT EXISTS invoices ();

ALTER TABLE invoices ADD IF NOT EXISTS id VARCHAR;
ALTER TABLE invoices ADD IF NOT EXISTS title VARCHAR;
ALTER TABLE invoices ADD IF NOT EXISTS platform VARCHAR;
ALTER TABLE invoices ADD IF NOT EXISTS begin_date DATE;
ALTER TABLE invoices ADD IF NOT EXISTS due_date DATE;
ALTER TABLE invoices ADD IF NOT EXISTS roi NUMERIC;

