

ALTER TABLE IF EXISTS invoices DROP COLUMN IF EXISTS roi;
ALTER TABLE IF EXISTS invoices DROP COLUMN IF EXISTS due_date;
ALTER TABLE IF EXISTS invoices DROP COLUMN IF EXISTS begin_date;
ALTER TABLE IF EXISTS invoices DROP COLUMN IF EXISTS platform;
ALTER TABLE IF EXISTS invoices DROP COLUMN IF EXISTS title;
ALTER TABLE IF EXISTS invoices DROP COLUMN IF EXISTS id;

DROP TABLE IF EXISTS invoices;

